### ISSUE TITLE
Why does it print "xxx" when I select ColorRow? Should it even be selectable?

### ISSUE THREAD

**Issue by Sweeper777** [alldritt/EurekaColorPicker#1]
I found these lines at ColorRow.swift line 49:

    open override func didSelect() {
        print("xxx")
        
    }

Why print xxx? Was this for debugging and you forgot to remove it? Also, `ColorRow` is supposed to be a row that displays a color only, just like a `LabelRow` displays text, right? Why is it even selectable in the first place?

**Comment by alldritt** [comment]
You are correct.  ColorRow is display only, just like LabelRow, and should not be selectable and should not have a didSelect block.  Thanks for the heads up and I apologize for the confusion.

**Comment by alldritt** [comment]
the `didSelect()` code has been removed.
