### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by gbread** [alldritt/EurekaColorPicker#11]
I'm having iOS 11 and your lib is not buildable. 
Fix is easy, just rename a few things so its not worth it for a new contribution :D 
Thanks for fixing

**Comment by alldritt** [comment]
What exactly is the problem you are experiencing?  Please cite error messages or something else which would help me understand your problem.

If the issue is that you are still using Xcode 9 and Swift 4.1, then just use version 1.2.2 which was the last Xcode 9 release.

**Comment by gbread** [comment]
My mistake then, sorry :D
