### ISSUE TITLE
Can't use palettes with InlineColorPickerRow

### ISSUE THREAD

**Issue by meoz** [alldritt/EurekaColorPicker#16]
Works fine with ColorPickerRow but InlineColorPickerRow always shows the default palettes even when setting a custom palette like this:

            <<< InlineColorPickerRow("colorcode") { (row) in
                row.title = "Color Code"
                row.isCircular = true
                row.showsPaletteNames = false
                row.value = UIColor.white
                }
                .cellSetup { (cell, row) in
                    let palette = ColorPalette(name: "All",
                                               palette: [ColorSpec(hex: "#ffffff", name: "White"),
                                                         ColorSpec(hex: "#000000", name: "Black")])
                    row.inlineRow?.cell.palettes = [palette]
            }

**Comment by alldritt** [comment]
Use the `palettes` property of the `InlineColorPickerRow` instance instead:

                <<< InlineColorPickerRow("colorcode") { (row) in
                    row.title = "Color Code"
                    row.isCircular = true
                    row.showsPaletteNames = false
                    row.value = UIColor.white
                    let palette = ColorPalette(name: "All",
                                               palette: [ColorSpec(hex: "#ffffff", name: "White"),
                                                         ColorSpec(hex: "#000000", name: "Black")])
                    row.palettes = [palette]
                }

**Comment by meoz** [comment]
Thanks !!
