### ISSUE TITLE
I can't install pod

### ISSUE THREAD

**Issue by wammy67** [alldritt/EurekaColorPicker#17]
```
[!] CocoaPods could not find compatible versions for pod "ColorPickerRow":
  In Podfile:
    ColorPickerRow

Specs satisfying the `ColorPickerRow` dependency were found, but they required a higher minimum deployment target.

```
responds console when I'm trying to install pods

**Comment by wammy67** [comment]
I'm trying to build it on iOS 12.2

**Comment by alldritt** [comment]
I'm using a 10.0 deployment target without any problems.  Can you show me your Podfile?

**Comment by wammy67** [comment]
<img width="716" alt="Screen Shot 2019-09-10 at 10 22 47" src="https://user-images.githubusercontent.com/30232021/64589090-4d3e9880-d3b5-11e9-8d1b-47a1bf44553c.png">

as I later discovered problem was in line 2:
platform :ios, '9.0'. as I bumped 9.0 to 11.0 problem was solved.
