### ISSUE TITLE
Eureka ~> 4.0 support

### ISSUE THREAD

**Issue by mtnbarreto** [alldritt/EurekaColorPicker#4]
@alldritt  could you release a new version that supports Eureka ~>4.0 ?

**Comment by alldritt** [comment]
It should be good now.  Just update your Podfile to use Eureka ~> 4.0.0 and update:

~~~
    pod 'Eureka', '~> 4.0.0'
    pod 'ColorPickerRow', :git => 'https://github.com/EurekaCommunity/ColorPickerRow'  
    pod 'UIColor_Hex_Swift'
~~~

However, I've updated the example application to use Eureka 4.  You can see that in the Eureka4 branch.  I'll merge that into master in the next few days.

**Comment by alldritt** [comment]
I've merged changes to the Example application supporting Eureka 4, Xcode 9 and Swift 4.
